name: vazamento_detector
description: Aplicativo de vistoria visual usando camera e analise assistida.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  image: ^4.5.4
  tflite_flutter: ^0.12.1
  async: ^2.11.0
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
